etcd-stateful:
  replicaCount: 3
  etcd:
    resources:
      limits:
        memory: 512Mi

global:
  isLocalEnv: false
  containerRegistry:
    path: eu.gcr.io/kyma-project
  istio:
    gateway:
      name: kyma-gateway
  etcdBackup:
    enabled: false
    secretName: etcd-backup-abs-credentials
  etcd_backup_job:
    dir: develop/
    version: f8c8d3d6

service-catalog-apiserver:
  enabled: true
service-catalog-crds:
  enabled: false
